
package com.secusociale.portail.service.soap.reprise_activite_statut;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * CM-GetStatusRepriseActivite version 2: get status reprise activite
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CM-GetStatusRepriseActiviteService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetStatusRepriseActivite", wsdlLocation = "http://192.168.125.23:7500/ouaf/XAIApp/xaiserver/CM-GetStatusRepriseActivite?WSDL")
public class CMGetStatusRepriseActiviteService
    extends Service
{

    private final static URL CMGETSTATUSREPRISEACTIVITESERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGETSTATUSREPRISEACTIVITESERVICE_EXCEPTION;
    private final static QName CMGETSTATUSREPRISEACTIVITESERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetStatusRepriseActivite", "CM-GetStatusRepriseActiviteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.125.23:7500/ouaf/XAIApp/xaiserver/CM-GetStatusRepriseActivite?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGETSTATUSREPRISEACTIVITESERVICE_WSDL_LOCATION = url;
        CMGETSTATUSREPRISEACTIVITESERVICE_EXCEPTION = e;
    }

    public CMGetStatusRepriseActiviteService() {
        super(__getWsdlLocation(), CMGETSTATUSREPRISEACTIVITESERVICE_QNAME);
    }

    public CMGetStatusRepriseActiviteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGETSTATUSREPRISEACTIVITESERVICE_QNAME, features);
    }

    public CMGetStatusRepriseActiviteService(URL wsdlLocation) {
        super(wsdlLocation, CMGETSTATUSREPRISEACTIVITESERVICE_QNAME);
    }

    public CMGetStatusRepriseActiviteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGETSTATUSREPRISEACTIVITESERVICE_QNAME, features);
    }

    public CMGetStatusRepriseActiviteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMGetStatusRepriseActiviteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CMGetStatusRepriseActivitePortType
     */
    @WebEndpoint(name = "CM-GetStatusRepriseActivitePort")
    public CMGetStatusRepriseActivitePortType getCMGetStatusRepriseActivitePort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetStatusRepriseActivite", "CM-GetStatusRepriseActivitePort"), CMGetStatusRepriseActivitePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CMGetStatusRepriseActivitePortType
     */
    @WebEndpoint(name = "CM-GetStatusRepriseActivitePort")
    public CMGetStatusRepriseActivitePortType getCMGetStatusRepriseActivitePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetStatusRepriseActivite", "CM-GetStatusRepriseActivitePort"), CMGetStatusRepriseActivitePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGETSTATUSREPRISEACTIVITESERVICE_EXCEPTION!= null) {
            throw CMGETSTATUSREPRISEACTIVITESERVICE_EXCEPTION;
        }
        return CMGETSTATUSREPRISEACTIVITESERVICE_WSDL_LOCATION;
    }

}
