
package com.secusociale.portail.service.soap.cessation_suspension_statut;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * CM-GET_STATUS_CESSATION_SUSPENSION version 2: get status cessation and suspension activite
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CM-GET_STATUS_CESSATION_SUSPENSIONService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GET_STATUS_CESSATION_SUSPENSION", wsdlLocation = "http://192.168.125.23:7500/ouaf/XAIApp/xaiserver/CM-GET_STATUS_CESSATION_SUSPENSION?WSDL")
public class CMGETSTATUSCESSATIONSUSPENSIONService
    extends Service
{

    private final static URL CMGETSTATUSCESSATIONSUSPENSIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGETSTATUSCESSATIONSUSPENSIONSERVICE_EXCEPTION;
    private final static QName CMGETSTATUSCESSATIONSUSPENSIONSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GET_STATUS_CESSATION_SUSPENSION", "CM-GET_STATUS_CESSATION_SUSPENSIONService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.125.23:7500/ouaf/XAIApp/xaiserver/CM-GET_STATUS_CESSATION_SUSPENSION?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGETSTATUSCESSATIONSUSPENSIONSERVICE_WSDL_LOCATION = url;
        CMGETSTATUSCESSATIONSUSPENSIONSERVICE_EXCEPTION = e;
    }

    public CMGETSTATUSCESSATIONSUSPENSIONService() {
        super(__getWsdlLocation(), CMGETSTATUSCESSATIONSUSPENSIONSERVICE_QNAME);
    }

    public CMGETSTATUSCESSATIONSUSPENSIONService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGETSTATUSCESSATIONSUSPENSIONSERVICE_QNAME, features);
    }

    public CMGETSTATUSCESSATIONSUSPENSIONService(URL wsdlLocation) {
        super(wsdlLocation, CMGETSTATUSCESSATIONSUSPENSIONSERVICE_QNAME);
    }

    public CMGETSTATUSCESSATIONSUSPENSIONService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGETSTATUSCESSATIONSUSPENSIONSERVICE_QNAME, features);
    }

    public CMGETSTATUSCESSATIONSUSPENSIONService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMGETSTATUSCESSATIONSUSPENSIONService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CMGETSTATUSCESSATIONSUSPENSIONPortType
     */
    @WebEndpoint(name = "CM-GET_STATUS_CESSATION_SUSPENSIONPort")
    public CMGETSTATUSCESSATIONSUSPENSIONPortType getCMGETSTATUSCESSATIONSUSPENSIONPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GET_STATUS_CESSATION_SUSPENSION", "CM-GET_STATUS_CESSATION_SUSPENSIONPort"), CMGETSTATUSCESSATIONSUSPENSIONPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CMGETSTATUSCESSATIONSUSPENSIONPortType
     */
    @WebEndpoint(name = "CM-GET_STATUS_CESSATION_SUSPENSIONPort")
    public CMGETSTATUSCESSATIONSUSPENSIONPortType getCMGETSTATUSCESSATIONSUSPENSIONPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GET_STATUS_CESSATION_SUSPENSION", "CM-GET_STATUS_CESSATION_SUSPENSIONPort"), CMGETSTATUSCESSATIONSUSPENSIONPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGETSTATUSCESSATIONSUSPENSIONSERVICE_EXCEPTION!= null) {
            throw CMGETSTATUSCESSATIONSUSPENSIONSERVICE_EXCEPTION;
        }
        return CMGETSTATUSCESSATIONSUSPENSIONSERVICE_WSDL_LOCATION;
    }

}
