
package com.secusociale.portail.service.soap.infosEmployeur;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.secusociale.portail.service.PortailConstant;


/**
 * CM_INFOS_EMPLOYEUR version 2: infos employeur
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CM_INFOS_EMPLOYEURService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_INFOS_EMPLOYEUR", wsdlLocation = PortailConstant.INFOS_COMPTE_EMPLOYEUR_WSDL)
public class CMINFOSEMPLOYEURService
    extends Service
{

    private final static URL CMINFOSEMPLOYEURSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMINFOSEMPLOYEURSERVICE_EXCEPTION;
    private final static QName CMINFOSEMPLOYEURSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_INFOS_EMPLOYEUR", "CM_INFOS_EMPLOYEURService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(PortailConstant.INFOS_COMPTE_EMPLOYEUR_WSDL);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMINFOSEMPLOYEURSERVICE_WSDL_LOCATION = url;
        CMINFOSEMPLOYEURSERVICE_EXCEPTION = e;
    }

    public CMINFOSEMPLOYEURService() {
        super(__getWsdlLocation(), CMINFOSEMPLOYEURSERVICE_QNAME);
    }

    public CMINFOSEMPLOYEURService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMINFOSEMPLOYEURSERVICE_QNAME, features);
    }

    public CMINFOSEMPLOYEURService(URL wsdlLocation) {
        super(wsdlLocation, CMINFOSEMPLOYEURSERVICE_QNAME);
    }

    public CMINFOSEMPLOYEURService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMINFOSEMPLOYEURSERVICE_QNAME, features);
    }

    public CMINFOSEMPLOYEURService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMINFOSEMPLOYEURService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CMINFOSEMPLOYEURPortType
     */
    @WebEndpoint(name = "CM_INFOS_EMPLOYEURPort")
    public CMINFOSEMPLOYEURPortType getCMINFOSEMPLOYEURPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_INFOS_EMPLOYEUR", "CM_INFOS_EMPLOYEURPort"), CMINFOSEMPLOYEURPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CMINFOSEMPLOYEURPortType
     */
    @WebEndpoint(name = "CM_INFOS_EMPLOYEURPort")
    public CMINFOSEMPLOYEURPortType getCMINFOSEMPLOYEURPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_INFOS_EMPLOYEUR", "CM_INFOS_EMPLOYEURPort"), CMINFOSEMPLOYEURPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMINFOSEMPLOYEURSERVICE_EXCEPTION!= null) {
            throw CMINFOSEMPLOYEURSERVICE_EXCEPTION;
        }
        return CMINFOSEMPLOYEURSERVICE_WSDL_LOCATION;
    }

}
