
package com.secusociale.portail.service.soap.soldeEmployeur;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * XAI_GETSOLDE version 2: solde compte de l'employeur
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "XAI_GETSOLDEService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/XAI_GETSOLDE", wsdlLocation = "http://192.168.125.23:7500/ouaf/XAIApp/xaiserver/XAI_GETSOLDE?WSDL")
public class XAIGETSOLDEService
    extends Service
{

    private final static URL XAIGETSOLDESERVICE_WSDL_LOCATION;
    private final static WebServiceException XAIGETSOLDESERVICE_EXCEPTION;
    private final static QName XAIGETSOLDESERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/XAI_GETSOLDE", "XAI_GETSOLDEService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.125.23:7500/ouaf/XAIApp/xaiserver/XAI_GETSOLDE?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        XAIGETSOLDESERVICE_WSDL_LOCATION = url;
        XAIGETSOLDESERVICE_EXCEPTION = e;
    }

    public XAIGETSOLDEService() {
        super(__getWsdlLocation(), XAIGETSOLDESERVICE_QNAME);
    }

    public XAIGETSOLDEService(WebServiceFeature... features) {
        super(__getWsdlLocation(), XAIGETSOLDESERVICE_QNAME, features);
    }

    public XAIGETSOLDEService(URL wsdlLocation) {
        super(wsdlLocation, XAIGETSOLDESERVICE_QNAME);
    }

    public XAIGETSOLDEService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, XAIGETSOLDESERVICE_QNAME, features);
    }

    public XAIGETSOLDEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XAIGETSOLDEService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns XAIGETSOLDEPortType
     */
    @WebEndpoint(name = "XAI_GETSOLDEPort")
    public XAIGETSOLDEPortType getXAIGETSOLDEPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/XAI_GETSOLDE", "XAI_GETSOLDEPort"), XAIGETSOLDEPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XAIGETSOLDEPortType
     */
    @WebEndpoint(name = "XAI_GETSOLDEPort")
    public XAIGETSOLDEPortType getXAIGETSOLDEPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/XAI_GETSOLDE", "XAI_GETSOLDEPort"), XAIGETSOLDEPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (XAIGETSOLDESERVICE_EXCEPTION!= null) {
            throw XAIGETSOLDESERVICE_EXCEPTION;
        }
        return XAIGETSOLDESERVICE_WSDL_LOCATION;
    }

}
