
package com.secusociale.portail.service.soap.ficheEmployeur;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * CM-FICHEPORT_XAI version 2: ss fiche employer update
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CM-FICHEPORT_XAIService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-FICHEPORT_XAI", wsdlLocation = "http://192.168.125.23:7500/ouaf/XAIApp/xaiserver/CM-FICHEPORT_XAI?WSDL")
public class CMFICHEPORTXAIService
    extends Service
{

    private final static URL CMFICHEPORTXAISERVICE_WSDL_LOCATION;
    private final static WebServiceException CMFICHEPORTXAISERVICE_EXCEPTION;
    private final static QName CMFICHEPORTXAISERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-FICHEPORT_XAI", "CM-FICHEPORT_XAIService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.125.23:7500/ouaf/XAIApp/xaiserver/CM-FICHEPORT_XAI?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMFICHEPORTXAISERVICE_WSDL_LOCATION = url;
        CMFICHEPORTXAISERVICE_EXCEPTION = e;
    }

    public CMFICHEPORTXAIService() {
        super(__getWsdlLocation(), CMFICHEPORTXAISERVICE_QNAME);
    }

    public CMFICHEPORTXAIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMFICHEPORTXAISERVICE_QNAME, features);
    }

    public CMFICHEPORTXAIService(URL wsdlLocation) {
        super(wsdlLocation, CMFICHEPORTXAISERVICE_QNAME);
    }

    public CMFICHEPORTXAIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMFICHEPORTXAISERVICE_QNAME, features);
    }

    public CMFICHEPORTXAIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMFICHEPORTXAIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CMFICHEPORTXAIPortType
     */
    @WebEndpoint(name = "CM-FICHEPORT_XAIPort")
    public CMFICHEPORTXAIPortType getCMFICHEPORTXAIPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-FICHEPORT_XAI", "CM-FICHEPORT_XAIPort"), CMFICHEPORTXAIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CMFICHEPORTXAIPortType
     */
    @WebEndpoint(name = "CM-FICHEPORT_XAIPort")
    public CMFICHEPORTXAIPortType getCMFICHEPORTXAIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-FICHEPORT_XAI", "CM-FICHEPORT_XAIPort"), CMFICHEPORTXAIPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMFICHEPORTXAISERVICE_EXCEPTION!= null) {
            throw CMFICHEPORTXAISERVICE_EXCEPTION;
        }
        return CMFICHEPORTXAISERVICE_WSDL_LOCATION;
    }

}
