
package com.secusociale.portail.service.soap.reprise_activite_accuse_url;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * CM-GetUrlAccuseReceptionReprise version 2: Génération état reprise avec BI Publisher
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CM-GetUrlAccuseReceptionRepriseService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetUrlAccuseReceptionReprise", wsdlLocation = "http://192.168.125.23:7500/ouaf/XAIApp/xaiserver/CM-GetUrlAccuseReceptionReprise?WSDL")
public class CMGetUrlAccuseReceptionRepriseService
    extends Service
{

    private final static URL CMGETURLACCUSERECEPTIONREPRISESERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGETURLACCUSERECEPTIONREPRISESERVICE_EXCEPTION;
    private final static QName CMGETURLACCUSERECEPTIONREPRISESERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetUrlAccuseReceptionReprise", "CM-GetUrlAccuseReceptionRepriseService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.125.23:7500/ouaf/XAIApp/xaiserver/CM-GetUrlAccuseReceptionReprise?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGETURLACCUSERECEPTIONREPRISESERVICE_WSDL_LOCATION = url;
        CMGETURLACCUSERECEPTIONREPRISESERVICE_EXCEPTION = e;
    }

    public CMGetUrlAccuseReceptionRepriseService() {
        super(__getWsdlLocation(), CMGETURLACCUSERECEPTIONREPRISESERVICE_QNAME);
    }

    public CMGetUrlAccuseReceptionRepriseService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGETURLACCUSERECEPTIONREPRISESERVICE_QNAME, features);
    }

    public CMGetUrlAccuseReceptionRepriseService(URL wsdlLocation) {
        super(wsdlLocation, CMGETURLACCUSERECEPTIONREPRISESERVICE_QNAME);
    }

    public CMGetUrlAccuseReceptionRepriseService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGETURLACCUSERECEPTIONREPRISESERVICE_QNAME, features);
    }

    public CMGetUrlAccuseReceptionRepriseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMGetUrlAccuseReceptionRepriseService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CMGetUrlAccuseReceptionReprisePortType
     */
    @WebEndpoint(name = "CM-GetUrlAccuseReceptionReprisePort")
    public CMGetUrlAccuseReceptionReprisePortType getCMGetUrlAccuseReceptionReprisePort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetUrlAccuseReceptionReprise", "CM-GetUrlAccuseReceptionReprisePort"), CMGetUrlAccuseReceptionReprisePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CMGetUrlAccuseReceptionReprisePortType
     */
    @WebEndpoint(name = "CM-GetUrlAccuseReceptionReprisePort")
    public CMGetUrlAccuseReceptionReprisePortType getCMGetUrlAccuseReceptionReprisePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetUrlAccuseReceptionReprise", "CM-GetUrlAccuseReceptionReprisePort"), CMGetUrlAccuseReceptionReprisePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGETURLACCUSERECEPTIONREPRISESERVICE_EXCEPTION!= null) {
            throw CMGETURLACCUSERECEPTIONREPRISESERVICE_EXCEPTION;
        }
        return CMGETURLACCUSERECEPTIONREPRISESERVICE_WSDL_LOCATION;
    }

}
