
package com.secusociale.portail.service.soap.reprise_activite;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * CM-GET_INFOS_REPRISE version 2: Les agences de rattachement CSS et IPRES
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CM-GET_INFOS_REPRISEService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GET_INFOS_REPRISE", wsdlLocation = "http://192.168.125.23:7500/ouaf/XAIApp/xaiserver/CM-GET_INFOS_REPRISE?WSDL")
public class CMGETINFOSREPRISEService
    extends Service
{

    private final static URL CMGETINFOSREPRISESERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGETINFOSREPRISESERVICE_EXCEPTION;
    private final static QName CMGETINFOSREPRISESERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GET_INFOS_REPRISE", "CM-GET_INFOS_REPRISEService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.125.23:7500/ouaf/XAIApp/xaiserver/CM-GET_INFOS_REPRISE?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGETINFOSREPRISESERVICE_WSDL_LOCATION = url;
        CMGETINFOSREPRISESERVICE_EXCEPTION = e;
    }

    public CMGETINFOSREPRISEService() {
        super(__getWsdlLocation(), CMGETINFOSREPRISESERVICE_QNAME);
    }

    public CMGETINFOSREPRISEService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGETINFOSREPRISESERVICE_QNAME, features);
    }

    public CMGETINFOSREPRISEService(URL wsdlLocation) {
        super(wsdlLocation, CMGETINFOSREPRISESERVICE_QNAME);
    }

    public CMGETINFOSREPRISEService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGETINFOSREPRISESERVICE_QNAME, features);
    }

    public CMGETINFOSREPRISEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMGETINFOSREPRISEService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CMGETINFOSREPRISEPortType
     */
    @WebEndpoint(name = "CM-GET_INFOS_REPRISEPort")
    public CMGETINFOSREPRISEPortType getCMGETINFOSREPRISEPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GET_INFOS_REPRISE", "CM-GET_INFOS_REPRISEPort"), CMGETINFOSREPRISEPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CMGETINFOSREPRISEPortType
     */
    @WebEndpoint(name = "CM-GET_INFOS_REPRISEPort")
    public CMGETINFOSREPRISEPortType getCMGETINFOSREPRISEPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GET_INFOS_REPRISE", "CM-GET_INFOS_REPRISEPort"), CMGETINFOSREPRISEPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGETINFOSREPRISESERVICE_EXCEPTION!= null) {
            throw CMGETINFOSREPRISESERVICE_EXCEPTION;
        }
        return CMGETINFOSREPRISESERVICE_WSDL_LOCATION;
    }

}
