
package com.secusociale.portail.service.soap.facturesImpayes;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * FACTURES_IMPAYEES_SERVICE version 2: Factures impayées
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FACTURES_IMPAYEES_SERVICEService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/FACTURES_IMPAYEES_SERVICE", wsdlLocation = "http://192.168.125.23:7500/ouaf/XAIApp/xaiserver/FACTURES_IMPAYEES_SERVICE?WSDL")
public class FACTURESIMPAYEESSERVICEService
    extends Service
{

    private final static URL FACTURESIMPAYEESSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FACTURESIMPAYEESSERVICESERVICE_EXCEPTION;
    private final static QName FACTURESIMPAYEESSERVICESERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/FACTURES_IMPAYEES_SERVICE", "FACTURES_IMPAYEES_SERVICEService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.125.23:7500/ouaf/XAIApp/xaiserver/FACTURES_IMPAYEES_SERVICE?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FACTURESIMPAYEESSERVICESERVICE_WSDL_LOCATION = url;
        FACTURESIMPAYEESSERVICESERVICE_EXCEPTION = e;
    }

    public FACTURESIMPAYEESSERVICEService() {
        super(__getWsdlLocation(), FACTURESIMPAYEESSERVICESERVICE_QNAME);
    }

    public FACTURESIMPAYEESSERVICEService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FACTURESIMPAYEESSERVICESERVICE_QNAME, features);
    }

    public FACTURESIMPAYEESSERVICEService(URL wsdlLocation) {
        super(wsdlLocation, FACTURESIMPAYEESSERVICESERVICE_QNAME);
    }

    public FACTURESIMPAYEESSERVICEService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FACTURESIMPAYEESSERVICESERVICE_QNAME, features);
    }

    public FACTURESIMPAYEESSERVICEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FACTURESIMPAYEESSERVICEService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FACTURESIMPAYEESSERVICEPortType
     */
    @WebEndpoint(name = "FACTURES_IMPAYEES_SERVICEPort")
    public FACTURESIMPAYEESSERVICEPortType getFACTURESIMPAYEESSERVICEPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/FACTURES_IMPAYEES_SERVICE", "FACTURES_IMPAYEES_SERVICEPort"), FACTURESIMPAYEESSERVICEPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FACTURESIMPAYEESSERVICEPortType
     */
    @WebEndpoint(name = "FACTURES_IMPAYEES_SERVICEPort")
    public FACTURESIMPAYEESSERVICEPortType getFACTURESIMPAYEESSERVICEPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/FACTURES_IMPAYEES_SERVICE", "FACTURES_IMPAYEES_SERVICEPort"), FACTURESIMPAYEESSERVICEPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FACTURESIMPAYEESSERVICESERVICE_EXCEPTION!= null) {
            throw FACTURESIMPAYEESSERVICESERVICE_EXCEPTION;
        }
        return FACTURESIMPAYEESSERVICESERVICE_WSDL_LOCATION;
    }

}
