
package com.secusociale.portail.service.soap.facturesImpayes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FACTURES_IMPAYEES_SERVICEPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/FACTURES_IMPAYEES_SERVICE")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FACTURESIMPAYEESSERVICEPortType {


    /**
     * 
     * @param body
     * @throws FACTURESIMPAYEESSERVICEFault
     */
    @WebMethod(operationName = "FACTURES_IMPAYEES_SERVICE", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/FACTURES_IMPAYEES_SERVICE")
    public void facturesIMPAYEESSERVICE(
        @WebParam(name = "FACTURES_IMPAYEES_SERVICE", targetNamespace = "http://oracle.com/FACTURES_IMPAYEES_SERVICE.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<FACTURESIMPAYEESSERVICE> body)
        throws FACTURESIMPAYEESSERVICEFault
    ;

}
